In [2]:
import math
import pandas as pd
import numpy as np
from datetime import datetime
import datetime
print("i")

i

In [3]:
# set blank input
surge_input = pd.DataFrame(columns = ["date", "MedSurg_patients", "ICU_not_vent", "ICU_vent"])

surge_input

Empty DataFrame
Columns: [date, MedSurg_patients, ICU_not_vent, ICU_vent]
Index: []

In [10]:
hospital_info = pd.DataFrame(columns=["date","covid","non_covid"])

# dates
start_date = datetime.date(2022,11,19)
all_days = []
num_days = 15
 
for day in range(num_days):
    date = (start_date + datetime.timedelta(days = day)).isoformat()
    all_days.append(date)
    
# add dates to hospital info df
hospital_info.date = all_days

# covid/non-covid cases (must be input manually)
#covid_counts = [8,10,12,10,12,14,12,12,13,14,13,12,11,11]
#non_covid_counts = [8,10,12,10,12,14,12,12,13,14,13,12,11,11]
#non_covid_counts = [9, 7, 14, 15, 13, 14, 14, 15, 16, 16, 17, 16, 17, 18]


# data from 12/4
covid_counts = [39,42,42,44,55,57,57,58,66,57,63,71,71,73,69]
non_covid_counts = [8,10,12,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan]


# add to hospital info df
hospital_info.covid = covid_counts
hospital_info.non_covid = non_covid_counts

# write to csv
hospital_info.to_csv("hospital_info.csv",index=False)

In [11]:
hospital_info

          date  covid  non_covid
0   2022-11-19     39        8.0
1   2022-11-20     42       10.0
2   2022-11-21     42       12.0
3   2022-11-22     44        NaN
4   2022-11-23     55        NaN
5   2022-11-24     57        NaN
6   2022-11-25     57        NaN
7   2022-11-26     58        NaN
8   2022-11-27     66        NaN
9   2022-11-28     57        NaN
10  2022-11-29     63        NaN
11  2022-11-30     71        NaN
12  2022-12-01     71        NaN
13  2022-12-02     73        NaN
14  2022-12-03     69        NaN